services:
  nextjs-app:
    container_name: nextjs-dev
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  express-server:
    container_name: express-dev
    build: ./server
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: ["node", "index.js"]
